### ISSUE TITLE
Error post installation

### ISSUE THREAD

**Issue by Manik-Taneja** [IlyaGusev/russ#2]
I can't seem to run the code because I keep getting the following error.
<img width="1468" alt="Screen Shot 2022-05-26 at 1 58 44 AM" src="https://user-images.githubusercontent.com/91532344/170435325-215be352-9e79-4883-97ee-d5be38fb3ca5.png">

**Comment by IlyaGusev** [comment]
Hi, here is the working example in Colab: https://colab.research.google.com/drive/1lxxvEQWMAOaSJFSDHo-799PsCjkRo_8R
I hope that will help.
